- vignettes/simple-forecasts.Rmd
Change some configs for Canada data to achieve better performances
> Change config for Canada

- .github/CODEOWNERS
- .github/workflows/R-CMD-check.yaml
- R/epi_recipe.R
- tests/testthat/test-frosting.R
- tests/testthat/test-layer_predict.R
This is a test, but should really be all the changes we need for #47 .
> Add frosting to CI and sync with `main`

- R/frosting.R
- R/layer_predict.R
- man/add_frosting.Rd
- man/epi_workflow.Rd
- man/frosting.Rd
- man/layer_predict.Rd
As per [Issue 56](https://github.com/cmu-delphi/epipredict/issues/56), converted the tests for `layer_predict()` and for `frosting()` to some examples in the documentation.
> 56 convert the tests in layer predict and frosting to documentation ex

- DESCRIPTION
- R/blueprint-epi_recipe-default.R
- man/new_epi_recipe_blueprint.Rd
As best as I can tell, all our custom roles are now kept around by default rather than the previous runaround where they could be dropped in the bake step.
This is a hotfix to pass checks.
> bump hardhat dependency, removes bake_dependent_roles.

- R/epi_shift_internal.R
- man/step_epi_shift.Rd
- tests/testthat/test-epi_shift_internal.R
> Km kill lags good2

- DESCRIPTION
- data-raw/case_death_rate_subset.R
- musings/example-recipe.R
Tied to https://github.com/cmu-delphi/epidatr/issues/31.  To be merged after https://github.com/cmu-delphi/epidatr/pull/39 and maybe https://github.com/cmu-delphi/epiprocess/pull/187.  Also includes a change from dajmcdon/epiprocess -> cmu-delphi/epiprocess --- especially need to check that this doesn't break anything!
> Use renamed delphi.epidata package epidatr + cmu-delphi/'s epiprocess

- R/step_population_scaling.R
- man/step_population_scaling.Rd
- tests/testthat/test-population_scaling.R
Made adjustments based on the remaining comments in closed PR: https://github.com/cmu-delphi/epipredict/pull/112
> population scaling function adjustments

- DESCRIPTION
- R/create-layer.R
- R/layer_add_forecast_date.R
- R/layer_add_target_date.R
- R/layer_naomit.R
- R/layer_point_from_distn.R
- R/layer_population_scaling.R
- R/layer_predict.R
- R/layer_predictive_distn.R
- R/layer_quantile_distn.R
- R/layer_residual_quantiles.R
- R/layer_threshold_preds.R
- R/layers.R
- R/utils_arg.R
- man/add_layer.Rd
- man/layer_naomit.Rd
- man/layer_population_scaling.Rd
- man/layer_predict.Rd
- man/layer_predictive_distn.Rd
- man/layer_residual_quantiles.Rd
- man/layer_threshold.Rd
> Remove flag

- DESCRIPTION
- R/blueprint-epi_recipe-default.R
- tests/testthat/test-blueprint.R
In `hardhat`, The `check_is_data_like()` fun was removed, and replaced with `coerce_to_tibble()` by [PR 227](https://github.com/tidymodels/hardhat/pull/227). This stripped out the `epi_df` class. We avoid that now. Also requires hardhat >= 1.3.0.
> Tidy hotfix

- data-raw/case_death_rate_subset.R
- musings/example-recipe.R
- vignettes/preprocessing-and-models.Rmd
Resolves breaking change from upstream cmu-delphi/epidatr#99.  We "can't" `>=` the epidatr version dependency to try to get people better error messages because old versions hanging around are tagged "1.0.0" or maybe also "0.5.0", and we don't want to call the new version with this change something > "1.0.0".
> Update to latest `epidatr` (`fetch_tbl` -> `fetch`)

- R/make_quantile_reg.R
Addresses #213 so that users may be able to use the epipredict package in lower versions of R. To do this, in `make_quantile_reg()` removed `simplify = FALSE` and wrapped apply in  `unname(as.list(as.data.frame()))`, so that we get a list that looks to be compatible with `dist_quantiles()` - similar in format to the documentation example given there.
> Possible fix so that people may be able to use lower versions of R

- R/get_test_data.R
- R/layer_population_scaling.R
- R/step_population_scaling.R
- man/layer_population_scaling.Rd
- man/step_population_scaling.Rd
- tests/testthat/test-get_test_data.R
- tests/testthat/test-population_scaling.R
Addresses Issue #199 (modified `get_test_data()` function + added a test). Basically, omitted the end rows according to the min # of lags in the recipe when that's not 0.
> Modified `get_test_data()` to omit excess rows when lag != 0

- R/layer_population_scaling.R
- R/step_population_scaling.R
- R/utils-arg.R
- R/zzz.R
- tests/testthat/test-population_scaling.R
fixes #222. Hopefully the tests are fairly self explanatory. All this had to do was remove any column in the auxillary `df` and not in the main data frame, instead of _just_ the population column.
> fix: #222 don't add extra columns in `step_population_scaling` or `layer_population_scaling`

- .github/workflows/R-CMD-check.yaml
Using the quick fix suggested by @dsweber2.
This only enables the checks on pushes & PRs to v0.0.6.  If PRs to v0.0.6 are merged, this will NOT update the pkgdown site.  @dajmcdon Would we be merging to v0.0.6 & want the pkgdown site to be updated?
> Set R-CMD-check to run on push & PR to v0.0.6

- R/cdc_baseline_forecaster.R
- R/flusight_hub_formatter.R
- man/cdc_baseline_args_list.Rd
- man/flusight_hub_formatter.Rd
Closes #249 
Closes #251 
Additionally alters the `cdc_baseline_args_list()` defaults to match.
> V0.0.6 cleanup

- DESCRIPTION
- NEWS.md
- R/layer_residual_quantiles.R
- tests/testthat/test-layer_residual_quantiles.R
> simplify grab_residuals

- R/canned-epipred.R
- R/epi_recipe.R
- R/epi_workflow.R
- R/frosting.R
- R/workflow-printing.R
- vignettes/articles/sliding.Rmd
- vignettes/epipredict.Rmd
- vignettes/preprocessing-and-models.Rmd
> 277 recipe printing bug

- vignettes/update.Rmd
Here's a vignette that goes over how to use the add/remove/update, adjust and tidy functions that were recently added to the package.
> Vignette on the add_*/remove_*/update_*, adjust_* and tidy functions

- .github/pull_request_template.md
- .github/workflows/pkgdown.yaml
- DEVELOPMENT.md
- NEWS.md
Identical to https://github.com/cmu-delphi/epiprocess/pull/398 (and adjacent changes).
TODO:
> feat: versioning instructions in documentation and pkgdown ci

- README.Rmd
- README.md
Please:
-   [x] Make sure this PR is against "dev", not "main".
dajmcdon.
-   [x] Makes sure to bump the version number in `DESCRIPTION` and `NEWS.md`.
-   [x] Describe changes made in NEWS.md, making sure breaking changes
Just documentation updates to the README. I searched for references of install in the docs and this is the main place …
> doc: update installation instructions to reference stable branch

- _pkgdown.yml
Please:
-   [x] Make sure this PR is against "dev", not "main".
dajmcdon.
-   [ ] Makes sure to bump the version number in `DESCRIPTION` and `NEWS.md`.
-   [ ] Describe changes made in NEWS.md, making sure breaking changes
> adjust pkgdown to match epiprocess

- .Rbuildignore
- .lintr
- NEWS.md
- R/arx_forecaster.R
- R/layer_residual_quantiles.R
- tests/testthat/test-dist_quantiles.R
- tests/testthat/test-layer_residual_quantiles.R
- tests/testthat/test-target_date_bug.R
Please:
-   [ ] ~~Make sure this PR is against "dev", not "main".~~
dajmcdon.
-   [ ] ~~Makes sure to bump the version number in `DESCRIPTION` and `NEWS.md`.
version number (the second number).~~
-   [x] Describe changes made in NEWS.md, making sure breaking changes
Addresses some additional bugs in #290, merge into #300
> fix: more bugs in #290

- .github/pull_request_template.md
- DEVELOPMENT.md
Please:
-   [x] Make sure this PR is against "dev", not "main".
dajmcdon.
-   [ ] ~~Makes sure to bump the version number in `DESCRIPTION` and `NEWS.md`.
version number (the second number).~~
-   [ ] ~~Describe changes made in NEWS.md, making sure breaking changes
0.7.2, then write your changes under the 0.8 heading).~~
Adds a reminder about epiprocess version pinning to the docs here.
-   Resolves #292
> doc: add reminder about pinning epiprocess version in PR template

- NEWS.md
- R/arx_forecaster.R
- R/canned-epipred.R
Please:
-   [x] Make sure this PR is against "dev", not "main".
dajmcdon.
-   [x] Makes sure to bump the version number in `DESCRIPTION` and `NEWS.md`.
-   [x] Describe changes made in NEWS.md, making sure breaking changes
Update the predictor default to the value of the outcome arg in `arx_forecaster`.
-   Resolves #298
> refactor: update arx_forecaster predictor arg

- DESCRIPTION
- NEWS.md
- R/arx_classifier.R
- R/arx_forecaster.R
- man/arx_class_epi_workflow.Rd
- man/arx_fcast_epi_workflow.Rd
- man/autoplot-epipred.Rd
Please:
dajmcdon.
`arx_fcast_epi_workflow()` and `arx_class_epi_workflow()` now default to `trainer = parsnip::logistic_reg()` to match their more canned versions.
> refactor: consistent default for trainer arg

- .github/workflows/pkgdown.yaml
Please:
dajmcdon.
version number (the second number).~~
0.7.2, then write your changes under the 0.8 heading).~~
From the discussion earleir
- Resolves #327
> ci: stop running pkgdown on every commit

- R/step_growth_rate.R
- R/step_lag_difference.R
- man/step_growth_rate.Rd
- man/step_lag_difference.Rd
- tests/testthat/test-check_enough_train_data.R
- tests/testthat/test-step_training_window.R
Please:
dajmcdon.
Adds  step_epi_naomit to get rid of NAs.
- Resolves #347
> doc: fix step_lag_difference example

- DESCRIPTION
- NEWS.md
- R/epi_recipe.R
- tests/testthat/test-epi_recipe.R
Please:
dajmcdon.
Only allows epi_df in epi_recipe and everything else just gives a clear error as such. Open to conversation about this, I don't know if falling back to regular recipes is useful sometimes, I haven't needed that functionality, but if it's not, then this is the behavior I …
> refactor: epi_recipe only accepts epi_df

- DESCRIPTION
- NEWS.md
- vignettes/articles/sliding.Rmd
Please:
dajmcdon.
- Resolves #366
> fixing guess_time_type error

- R/make_quantile_reg.R
- man/quantile_reg.Rd
Please:
dajmcdon.
Allows us to choose the fitting method used by `quantilereg::rq`.
- Resolves #{issue number}
> feat: expose "method" arg of quantile_reg

- DESCRIPTION
This is just to make sure that epiprocess is pinned once the changes there happen and we don't have them updated here.
> make internal versioning accurate

- vignettes/articles/sliding.Rmd
- vignettes/articles/smooth-qr.Rmd
- vignettes/articles/symptom-surveys.Rmd
Please:
dajmcdon.~~
Fixed the sliding.Rmd article and verified the others. It needed a lot of work, because we can no longer use epi_slide to do geo-pooled forecasting because it requires you to apply the slide per group (fortunately the fix is easy - just make an archive out of the latest …
> doc: fix sliding article and verify others

- .github/workflows/pkgdown.yaml
- tests/testthat/_snaps/population_scaling.md
- tests/testthat/_snaps/step_epi_slide.md
- tests/testthat/test-grf_quantiles.R
- tests/testthat/test-snapshots.R
Please:
dajmcdon.
The [documentation on main](https://cmu-delphi.github.io/epipredict/) didn't get updated as intended. This syncs the pkgdown action to what's used in [epiprocess](https://github.com/cmu-delphi/epiprocess/blob/dev/.github/workflows/pkgdown.yaml), where we're sure it works.
- …
> ci: fix pkgdown

- .github/workflows/pkgdown.yaml
- tests/testthat/_snaps/step_epi_slide.md
Please:
dajmcdon.
This has the exact same fix as #404, except:
- it is based on `main`, not `dev`, so it doesn't contain the adjustAhead stuff, so we can just merge to main
- later when we merge dev into main _i think_ it will just notice that these commits are already in main, so it shouldn't …
> ci: fix ci

- vignettes/articles/scorecaster.Rmd
Please:
dajmcdon.
- Resolves #{issue number}
> Scorecaster

- DESCRIPTION
- data-raw/case_death_rate_subset.R
- data-raw/state_census.R
- tests/testthat/_snaps/population_scaling.md
- tests/testthat/_snaps/step_epi_slide.md
- tests/testthat/test-grf_quantiles.R
- tests/testthat/test-snapshots.R
Please:
dajmcdon.
* just download the state data file, don't import covidcast
* covidcast depends on sf which is tough to install (it just refuses to compile on my machine) and my renv keeps trying to install ALL dependencies
- Resolves #{issue number}
> refactor: remove Suggests dependence on covidcast

- vignettes/articles/smooth-qr.Rmd
- vignettes/articles/symptom-surveys.Rmd
Please:
dajmcdon.
Define `case_num` to keep vignette build from failing. Although it's no longer used for generating data, it is used in plot text.
> Define `case_num` var when pulling data from `epidatasets` in symptoms survey vignette

- .github/workflows/doc-preview.yaml
Please:
dajmcdon.
Adds /preview-docs command to help with docs review
- Resolves #{issue number}
> ci: add docs preview

- DESCRIPTION
- NEWS.md
- R/epi_recipe.R
Please:
dajmcdon.
- Resolves #438
> fix: update recipes internal function name

- R/climatological_forecaster.R
- R/layer_threshold_preds.R
- R/step_climate.R
- man/step_adjust_latency.Rd
- tests/testthat/test-step_climate.R
This adds some documentation and code comments.
The one feature addition so far is defaulting `time_type` to matching the `time_type` of the `epi_df` for `step_climate`
> Climate suggestions

- DESCRIPTION
- NEWS.md
- R/flusight_hub_formatter.R
- man/autoplot-epipred.Rd
- man/step_adjust_latency.Rd
Please:
dajmcdon.
Qualifies the namespace for `epidatasets::state_census` in two internal functions. The alternative would be to import that name, but qualifying the namespace seems better given that it is only used twice in the codebase.
- Resolves #469
> Fix flusight hub formatter
